baseURL = 'https://ngeranio.com/'
languageCode = 'en-us'
title = 'Lets Talk Networking Staff'
theme = 'blowfish'

# Add any links to things in /content/ here
[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Protocols"
url = "/protocols/"
weight = 2

# Enable this for Tailwind in markdown files
[markup.goldmark.renderer]
unsafe=true
